language: python
install:
  - pip install -r requirements.txt
python:
  - 3.5
  - 3.6
script:
  - python -m unittest discover
env:
  - LEANCLOUD_APP_ID=MdYmVQcBImbvesIujDhqxByR-gzGzoHsz
  - LEANCLOUD_APP_KEY=NwJgS8gDNuUclxaXVuuv395i